services:
  - type: web
    name: cipher-circuit-server
    runtime: node
    buildCommand: npm --prefix cipher-circuit/server install
    startCommand: node cipher-circuit/server/index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://aashish:bharatloveyash123@cluster0.imz3xfm.mongodb.net/ieee-circuit-cafe?appName=Cluster0&retryWrites=true&w=majority
      - key: DB_NAME
        value: ieee-circuit-cafe
      - key: JWT_SECRET
        value: cipher-circuit-secret-key-2026-ieee
